branches:
  only:
  - master
  - preview
sudo: false
language: node_js
cache:
  directories:
  - node_modules
node_js:
- stable
- 6.9.1
- 8.15.0
- 10.15.3
script: npm run build

jobs:
  include:
  - stage: npm release
    node_js: stable
    deploy:
    - provider: npm
      email: "wictor@wictorwilen.se"
      api_key:
        secure: E5KQERBzNNvBGsMU2ts2Xi6cvcCBHV5otcjpS8DKApLhnZ69w57hcOjfxDV8XJTyeyKXp2XxSaOXLHKfhgXtE1d0QZFe2AX2JG1TQvnhYAssE53hgExKST6G0R85WTctWjytYOidCfCi5mxPxlpn+N4R/GiYR9Z4GnLi5NWTm1smwmZIOQu/x8gIHmCpGeDIGutKqgqMzr94PXzs1xT3Q02HYWv55bfPLLMoHRo7t3KQBuQmVnMsQneS1phJBziamAgwiZ8PRBDithQlB6SCMaYPaHNp2FvS3+jWDe9pTDauF74X+4ZYiWEpeFAin2IuWtzCPxhoQtdXWHCjUMiN8DLayVqprLgZrC3StEZgwLB9SaJqqe2d1QB/XPJBx5UjXp5gDlpG0HFaFbzlNh3p3RXdbHq4Cu+czEcoPwYBi7yEKxQxvsyZ+WnsZFnscq86kexRlXQPOIMUWRH5i/kJLDSZm2+ByDzK8mT6j9lYCtkvppvIocQw9HKdqdpgpzwTmYLeHTh2XngCF7ToZemfkrPA2u6dkuAPgzwEhCpEkNXHdzN00nUIs0lhJfqSPbakRamydERyOCYl0nAWTrOwcI4qwRtTvBklUgEA/EQ6mJFdf0HqgYzMjlCiXqA1D1VsKrwRGI/O/5suljTqktFFbHUW37uNZybBwzL15eatOU0=
      skip_cleanup: true
      tag: preview
      on:
        branch: preview
    - provider: npm
      email: "wictor@wictorwilen.se"
      api_key:
        secure: E5KQERBzNNvBGsMU2ts2Xi6cvcCBHV5otcjpS8DKApLhnZ69w57hcOjfxDV8XJTyeyKXp2XxSaOXLHKfhgXtE1d0QZFe2AX2JG1TQvnhYAssE53hgExKST6G0R85WTctWjytYOidCfCi5mxPxlpn+N4R/GiYR9Z4GnLi5NWTm1smwmZIOQu/x8gIHmCpGeDIGutKqgqMzr94PXzs1xT3Q02HYWv55bfPLLMoHRo7t3KQBuQmVnMsQneS1phJBziamAgwiZ8PRBDithQlB6SCMaYPaHNp2FvS3+jWDe9pTDauF74X+4ZYiWEpeFAin2IuWtzCPxhoQtdXWHCjUMiN8DLayVqprLgZrC3StEZgwLB9SaJqqe2d1QB/XPJBx5UjXp5gDlpG0HFaFbzlNh3p3RXdbHq4Cu+czEcoPwYBi7yEKxQxvsyZ+WnsZFnscq86kexRlXQPOIMUWRH5i/kJLDSZm2+ByDzK8mT6j9lYCtkvppvIocQw9HKdqdpgpzwTmYLeHTh2XngCF7ToZemfkrPA2u6dkuAPgzwEhCpEkNXHdzN00nUIs0lhJfqSPbakRamydERyOCYl0nAWTrOwcI4qwRtTvBklUgEA/EQ6mJFdf0HqgYzMjlCiXqA1D1VsKrwRGI/O/5suljTqktFFbHUW37uNZybBwzL15eatOU0=
      skip_cleanup: true
      on:
        branch: master
