branches:
  only:
  - master
  - preview
sudo: false
language: node_js
cache:
  directories:
  - node_modules
node_js:
- stable
- 6.9.1
- 8.15.0
- 10.15.3
script: npm run build
jobs:
  include:
  - stage: npm release
    node_js: stable
    deploy:
    - provider: npm
      email: wictor@wictorwilen.se
      api_key:
        secure: j36RaLpX2hQi8XzMG76gsG5kZc8Hn66hLEoGjaCuLXMIJPLC8VcsDvNP7p5tIq+J+vPK/ANJ5yEE6NwVSKfr5RYTiNgpZX/4RP5pnGLGLpMxuWRE2sEMYEz243+4DJ/JDWyY2b1JK6SECfXVyBUSRgo9PNJbtx+gkn34ulRbSDMKBEIdW981w/sB2GtpBm7G50PWjp3ILFUvJtN/G+lHy0DqovU3BGujhKoW+LqGABx80u3J2dz2cdGU9qxHnfkAkOURxykJXr5+3ASW6ugnWQhXrcY5EZscfuAnMhwXTxkP2oAq943ML+ZXFhfwKY+T3OnhHrKbvnKSPReFcABAZT9Oh53yQzSwVwzTjKcWb5VJSZh5dhG9KuikJGD3q6iXep2dRIVLze2NQi5fN0Y1+/UhHWUYM3hpkfiRq293rQAsF60DCBZUgxefLGalVzbpblK5hpBV7P+QIsDxop3phIpbE8o2FG65ozzUKjene3I+g9cJxfzKzuNgPn2hQSOEgUeUQw+lDngMi5CfFHHDBF9vvsUngk/1uK1J0JzKGIQGy3X+kNJkeAr8bcxih2yy8fqnu/CJBn/zUVdHaeVM5ePduvA7rVdPnIAqV5A93BlpaGjDhsl0pgtwscnjXGUAPVl8d4Yn4YNYwHOR18SZ/+R6JqYVZle7DQfgdrANilM=
      skip_cleanup: true
      tag: preview
      on:
        branch: preview
        tags: true
    - provider: npm
      email: wictor@wictorwilen.se
      api_key:
        secure: j36RaLpX2hQi8XzMG76gsG5kZc8Hn66hLEoGjaCuLXMIJPLC8VcsDvNP7p5tIq+J+vPK/ANJ5yEE6NwVSKfr5RYTiNgpZX/4RP5pnGLGLpMxuWRE2sEMYEz243+4DJ/JDWyY2b1JK6SECfXVyBUSRgo9PNJbtx+gkn34ulRbSDMKBEIdW981w/sB2GtpBm7G50PWjp3ILFUvJtN/G+lHy0DqovU3BGujhKoW+LqGABx80u3J2dz2cdGU9qxHnfkAkOURxykJXr5+3ASW6ugnWQhXrcY5EZscfuAnMhwXTxkP2oAq943ML+ZXFhfwKY+T3OnhHrKbvnKSPReFcABAZT9Oh53yQzSwVwzTjKcWb5VJSZh5dhG9KuikJGD3q6iXep2dRIVLze2NQi5fN0Y1+/UhHWUYM3hpkfiRq293rQAsF60DCBZUgxefLGalVzbpblK5hpBV7P+QIsDxop3phIpbE8o2FG65ozzUKjene3I+g9cJxfzKzuNgPn2hQSOEgUeUQw+lDngMi5CfFHHDBF9vvsUngk/1uK1J0JzKGIQGy3X+kNJkeAr8bcxih2yy8fqnu/CJBn/zUVdHaeVM5ePduvA7rVdPnIAqV5A93BlpaGjDhsl0pgtwscnjXGUAPVl8d4Yn4YNYwHOR18SZ/+R6JqYVZle7DQfgdrANilM=
      skip_cleanup: true
      on:
        branch: master
        tags: true

